require 'active_record'
require 'action_controller'
require 'rails/engine'
require 'sass-rails'
require 'coffee-rails'
require 'compass-rails'

require 'ponytail/routing/mapper'
require 'ponytail/config'
require 'ponytail/engine'
